name: ci/cd

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run prettier-check:updated
      - run: npm run lint:updated
